name: snap_floater
description: A draggable floating button for Flutter that snaps to predefined
  screen positions. Controlled programmatically from anywhere in the widget tree
  via `SnapFloaterScope.of(context)`.
version: 0.1.9
homepage: https://github.com/pavluke/snap_floater
repository: https://github.com/pavluke/snap_floater
issue_tracker: https://github.com/pavluke/snap_floater/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pavluke_lints: ^1.2.1

flutter:
  uses-material-design: true
